<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>f2f88163-38b1-40fc-ae0c-e9d7634f42c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tab-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d1a3931-1670-4a7d-896c-4a46388e3d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vuln.cilsy.id/member/signin</value>
      <webElementGuid>cf163da8-df46-446d-83f0-3e20ece3742c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-2</value>
      <webElementGuid>12b7ec51-aa92-4fa1-890c-ce6ae0844c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>91539b9c-87e4-472d-87f5-8010c2a7bc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-2&quot;)</value>
      <webElementGuid>da1e2964-5fb5-4721-868b-59749693e794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tab-2']</value>
      <webElementGuid>9948e963-9eed-4602-b8ff-f3226a72177c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sign-container']/div/a[2]</value>
      <webElementGuid>8b6f93fd-d7c0-4818-9c59-d884727e8941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Masuk')])[3]</value>
      <webElementGuid>23f396f2-0f55-456d-aed6-76e36c740b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[4]/following::a[1]</value>
      <webElementGuid>9ac33bd9-f264-4c87-b494-1bfa06cad7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[3]/following::a[2]</value>
      <webElementGuid>9bbfbc8f-4dd2-4244-94ab-9270400f059a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/preceding::a[1]</value>
      <webElementGuid>dccd486b-e750-4f8d-9e39-7b6fd4915ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/preceding::a[1]</value>
      <webElementGuid>35603ef9-c0b2-4ccb-811c-1711659c56cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://vuln.cilsy.id/member/signin')])[4]</value>
      <webElementGuid>12e6e7dc-5801-4990-b972-d7aca62524af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]</value>
      <webElementGuid>58fca66c-35c3-41f1-9132-d789d324f50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://vuln.cilsy.id/member/signin' and @id = 'tab-2' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>5c51f528-980e-4903-948a-8dda320278d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
